### ISSUE TITLE
base_trainer._save_checkpoint error in Windows

### ISSUE THREAD

**Issue by borgesa** [victoresque/pytorch-template#11]
Hi,

The use of 'os.rename' when saving a new 'model_best' in 'base_trainer._save_checkpoint' raises an exception.

With reference to os.rename documentation: 

> 'On Windows, if dst already exists, OSError will be raised even if it is a file.' 

The function can be replaced with 'os.replace': 

> 'If you want cross-platform overwriting of the destination, use replace().'

Both quotes from https://docs.python.org/3.6/library/os.html

**Comment by borgesa** [comment]
Hi,

I believe this issue is solved with the one change I mention in my post. At least, it then runs nicely in Windows. I have not verified that the behavior is equivalent in Linux/MacOS, but it should be (based on the 'os' module documentation).

Do you agree with making this change?

**Comment by victoresque** [comment]
Sure, I overlooked the change, thanks for noticing

**Comment by borgesa** [comment]
Hi,

The issue should not be closed before the code is updated.

The following change to line 115 in /base/base_trainer.py is required:

**From:**
```python
os.rename(filename, os.path.join(self.checkpoint_dir, 'model_best.pth.tar'))
```
**To:**
```python
os.replace(filename, os.path.join(self.checkpoint_dir, 'model_best.pth.tar'))
```
