### ISSUE TITLE
Versioned Repository

### ISSUE THREAD

**Issue by MiaoDX** [victoresque/pytorch-template#42]
Hi,
This project seems really interesting, wondering if it proper to archive periodically, so we can use extract version of it.

**Comment by SunQpark** [comment]
Hi, @MiaoDX.
My personal opinion is that, this project is currently not being updated quite frequently, hence versioning will not much helpful.
Can you provide more details on your idea?

**Comment by MiaoDX** [comment]
Aha, fair point, I was thinking that more than one files being changed in around 14 days indicates the project is still under heavy reconstruction. I will close this issue now, and thanks for this project!
