### ISSUE TITLE
Distribute template as a pip package

### ISSUE THREAD

**Issue by egor-bogomolov** [victoresque/pytorch-template#43]
First of all, thanks for an amazing project!

It offers a lot of handy features but to use them one needs to copy the whole template every time (or am I missing something?). It would be nice to create a package, installable via pip or conda to write only the necessary additions in new projects. From the architecture perspective, I don't see any major obstacles. The users should only point get_instance calls to custom modules and files.

**Comment by SunQpark** [comment]
You will like my latest PR #40. It contains a python script to initialize a new project with only the essential files of template. I was just about to merge that PR to this master repository soon(maybe today or tomorrow).

I've also considered the PyPI packaging but cloning the repository seems better to me, considering that customization of template files becomes trickier if it is distributed from package installer.

Thank you for your interest, @egor-bogomolov.
