### ISSUE TITLE
In test.py i face error.

### ISSUE THREAD

**Issue by EzoBear** [victoresque/pytorch-template#51]
test.py code  : 
args = parser.parse_args()
    **config = ConfigParser(args) *origin code**
    **config = ConfigParser(parser) *proposal code**
main(config, args.resume)

class ConfigParser:
    def __init__(self, args, options='', timestamp=True):
        # parse default and custom cli options
        for opt in options:
            args.add_argument(*opt.flags, default=None, type=opt.type)
        **args = args.parse_args()**

In args = args.parse_args(), args is result of parser.parse_args() 
so i occurred error.
so i proposal changing ConfigParser(args) to ConfigParser(parser) in test.py

**Comment by SunQpark** [comment]
Fixed in PR #52. Thank you for reporting, @EzoBear.
