### ISSUE TITLE
Bugs in Resume Checkpoint 

### ISSUE THREAD

**Issue by chienyiwang** [victoresque/pytorch-template#57]
Thanks for the great work on this template.
However, in the base_trainer.py, there are two bugs while resuming checkpoints:
1. line 100: (I think this is related to #54, but you closed the issue without fixing it)
While resume training from saved checkpoints, there will be "reference before assignment" error on the not_improved_count variable.
2. line 165 and 171:
The sanity check here is invalid, as the config would be overwritten by the config.json of the saved checkpoint when parsing config (line 22 in parse_config.py)

**Comment by SunQpark** [comment]
Thank you for reporting these problems, @chienyiwang.
I'll start working on this soon.

**Comment by SunQpark** [comment]
I made PR #58 for this Issue. Could you review the changes @chienyiwang??

**Comment by chienyiwang** [comment]
Just reviewed. Thanks for the quick fix!
