### ISSUE TITLE
how can I add arg into config after data loading step

### ISSUE THREAD

**Issue by Chunpai** [victoresque/pytorch-template#77]
I write a custom dataset and dataloader. The nn's input_dim is determined by one attribute of dataset. However, it seems I can only set the input_dim in config file. Any way to achieve this ? Thanks.

**Comment by SunQpark** [comment]
`config.init_obj` function (defined [here](https://github.com/victoresque/pytorch-template/blob/a39a102914feace71ddd05b58d5e5a7c0e2c99dd/parse_config.py#L80-L108)) also accepts additional args, kwargs. So, I think you can use this on the `train.py` file, like
```python
input_dim = data_loader.dataset.input_dim
model = config.init_obj('arch', module_arch, input_dim=input_dim)
```

**Comment by Chunpai** [comment]
> `config.init_obj` function (defined [here](https://github.com/victoresque/pytorch-template/blob/a39a102914feace71ddd05b58d5e5a7c0e2c99dd/parse_config.py#L80-L108)) also accepts additional args, kwargs. So, I think you can use this on the `train.py` file, like
> 
> ```python
> input_dim = data_loader.dataset.input_dim
> model = config.init_obj('arch', module_arch, input_dim=input_dim)
> ```

Thank you very much, @SunQpark .
