### ISSUE TITLE
Passing an iterable from config.json

### ISSUE THREAD

**Issue by bobvo23** [victoresque/pytorch-template#86]
Hi, 
I was trying to config different learning rates for different subnetworks, so I wonder how could I achieve the following set up using the template.

The Pytorch Optimizer takes in an iterable without any keyword argument in this case, so I'm not sure how to configure that.

Example from Pytorch documenation
``` 
optimizer = optim.SGD([
                {'params': model.base.parameters()},
                {'params': model.classifier.parameters(), 'lr': 1e-3}
            ], lr=1e-2, momentum=0.9)
```
https://pytorch.org/docs/stable/optim.html

Shall it be like this?
```
subnet_list = [
                {'params': model.base.parameters()},
                {'params': model.classifier.parameters(), 'lr': 1e-3}
            ]
optimizer = config.init_obj('optimizer', torch.optim, subnet_list)
```

**Comment by SunQpark** [comment]
Yes, I think that should work.
As you can check, the [`init_obj`](https://github.com/victoresque/pytorch-template/blob/41dc06f6f8f3f38c6ed49f01ff7d89cd5688adc4/parse_config.py#L80-L93) take args and kwargs.

Maybe using keyword argument is better for clarity, so
```python
optimizer = config.init_obj('optimizer', torch.optim, params=subnet_list)
```

**Comment by bobvo23** [comment]
Hi,
It works! It was a bit difficult to get started but everything is working for me now.
Thanks @SunQpark
