### ISSUE TITLE
ReduceLROnPlateau lr_scheduler

### ISSUE THREAD

**Issue by MohamedA95** [victoresque/pytorch-template#89]
Hello, 
Thanks for your efforts, I am trying to use ReduceLROnPlateau lr_scheduler, but I got the following error
```python
Traceback (most recent call last):
  File "/home/T1/train.py", line 73, in <module>
    main(config)
  File "/home/T1/train.py", line 54, in main
    trainer.train()
  File "/home/T1/base/base_trainer.py", line 63, in train
    result = self._train_epoch(epoch)
  File "/home/T1/trainer/trainer.py", line 72, in _train_epoch
    self.lr_scheduler.step()
TypeError: step() missing 1 required positional argument: 'metrics'
```
Accourding to Pytorch [doc](https://pytorch.org/docs/stable/optim.html#torch.optim.lr_scheduler.ReduceLROnPlateau) it should be used like this:
``` python
>>> optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9)
>>> scheduler = ReduceLROnPlateau(optimizer, 'min')
>>> for epoch in range(10):
>>>     train(...)
>>>     val_loss = validate(...)
>>>     # Note that step should be called after validate()
>>>     scheduler.step(val_loss)
```
I guess to do so ```_valid_epoch(self, epoch):``` has to return val_loss or save it somewhere that the optimizer can access, Could you guide me on this?

**Comment by YiweiJiang2015** [comment]
One way to solve your problem and conform to the template philosophy is to integrate `loss` into `valid_metrics`. To do so, you have to customize the `MetricTracker` class under `util.py`. When it is done, you can access `val_loss` by `val_log.val_loss` in `train_epoch()`.

**Comment by MohamedA95** [comment]
Hello @YiweiJiang2015, Thanks for your support. Will work on it and try to make a pull request.

**Comment by MohamedA95** [comment]
Hello @YiweiJiang2015, while working on this I found out that in `_train_epoch()` `log` is a dictionary that already contains the resulting `{'loss', 'accuracy', 'top_k_acc', 'val_loss', 'val_accuracy', 'val_top_k_acc'}` can I use these values to step the scheduler?
